# Generated by Django 5.0.2 on 2025-02-24 18:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0004_applicationmetrics_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationmetrics',
            name='user',
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('job_description', models.TextField(blank=True)),
                ('application_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('interview_scheduled', 'Interview Scheduled'), ('interviewing', 'Interviewing'), ('offer_received', 'Offer Received'), ('rejected', 'Rejected'), ('accepted', 'Accepted'), ('withdrawn', 'Withdrawn')], default='applied', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('next_follow_up', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('salary_range', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('remote_option', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_applications',
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Call'), ('interview', 'Interview'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField()),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='job_applications.jobapplication')),
            ],
            options={
                'db_table': 'communications',
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='ApplicationMetrics',
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['user', '-application_date'], name='job_applica_user_id_376ee7_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['status'], name='job_applica_status_6d1402_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['-date'], name='communicati_date_22a785_idx'),
        ),
    ]
