# Generated by Django 5.0.2 on 2025-02-24 07:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0003_application_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_applications', models.IntegerField(default=0, help_text='Total number of applications sent')),
                ('response_rate', models.FloatField(default=0.0, help_text='Percentage of applications that received a response')),
                ('interview_rate', models.FloatField(default=0.0, help_text='Percentage of applications that led to interviews')),
                ('ghosted_rate', models.FloatField(default=0.0, help_text='Percentage of applications with no response')),
                ('avg_response_time', models.FloatField(default=0.0, help_text='Average number of days to receive a response')),
                ('best_companies', models.JSONField(default=dict, help_text='Companies with highest response rates')),
                ('worst_companies', models.JSONField(default=dict, help_text='Companies with lowest response rates')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when these metrics were calculated')),
            ],
            options={
                'db_table': 'application_metrics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='application',
            name='application_created_a07231_idx',
        ),
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp when the application was created'),
        ),
        migrations.AlterField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the application was last updated'),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(help_text='User who owns this application', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user', 'company_name', 'job_title'], name='application_user_id_ef8296_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user', 'status'], name='application_user_id_4cfcce_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('user', 'company_name', 'job_title'), name='unique_user_application'),
        ),
        migrations.AddField(
            model_name='applicationmetrics',
            name='user',
            field=models.ForeignKey(help_text='User who owns these metrics', on_delete=django.db.models.deletion.CASCADE, related_name='application_metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='applicationmetrics',
            index=models.Index(fields=['user', '-created_at'], name='application_user_id_b3f0a8_idx'),
        ),
    ]
